export type actionTypes =
  'GET_USER' | 'GET_USER_SUCCESS' | 'GET_USER_FAIL' |
  'INIT_CATALOG' | 'INIT_CATALOG_SUCCESS' | 'INIT_CATALOG_FAIL' |
  'GET_CART' | 'GET_CART_SUCCESS' | 'GET_CART_FAIL' |
  'SET_FILTER' | 'CLEAR_FILTERS' |
  'SET_SORT_BY';
